require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DictionariesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dictionary. As you add validations to Dictionary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {:name => "Norm's Vocabularly list", :language => "Greek"}
  end

  let(:invalid_attributes) do
    {:name => ""}
  end


  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DictionariesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dictionaries as @dictionaries" do
      dictionary = Dictionary.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:dictionaries)).to eq([dictionary])
    end
  end

  describe "GET #show" do
    it "assigns the requested dictionary as @dictionary" do
      dictionary = Dictionary.create! valid_attributes
      get :show, params: {id: dictionary.to_param}, session: valid_session
      expect(assigns(:dictionary)).to eq(dictionary)
    end
  end

  describe "GET #new" do
    it "assigns a new dictionary as @dictionary" do
      get :new, params: {}, session: valid_session
      expect(assigns(:dictionary)).to be_a_new(Dictionary)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dictionary as @dictionary" do
      dictionary = Dictionary.create! valid_attributes
      get :edit, params: {id: dictionary.to_param}, session: valid_session
      expect(assigns(:dictionary)).to eq(dictionary)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Dictionary" do
        expect {
          post :create, params: {dictionary: valid_attributes}, session: valid_session
        }.to change(Dictionary, :count).by(1)
      end

      it "assigns a newly created dictionary as @dictionary" do
        post :create, params: {dictionary: valid_attributes}, session: valid_session
        expect(assigns(:dictionary)).to be_a(Dictionary)
        expect(assigns(:dictionary)).to be_persisted
      end

      it "redirects to the created dictionary" do
        post :create, params: {dictionary: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Dictionary.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dictionary as @dictionary" do
        post :create, params: {dictionary: invalid_attributes}, session: valid_session
        expect(assigns(:dictionary)).to be_a_new(Dictionary)
      end

      it "re-renders the 'new' template" do
        post :create, params: {dictionary: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {:name => "Norms new vocab list", :language => "Italian"}
      end

      it "updates the requested dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, params: {id: dictionary.to_param, dictionary: new_attributes}, session: valid_session
        dictionary.reload
        expect(assigns(:dictionary).name).to eq(new_attributes[:name])
        expect(assigns(:dictionary).language).to eq(new_attributes[:language])

      end

      it "assigns the requested dictionary as @dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, params: {id: dictionary.to_param, dictionary: valid_attributes}, session: valid_session
        expect(assigns(:dictionary)).to eq(dictionary)
      end

      it "redirects to the dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, params: {id: dictionary.to_param, dictionary: valid_attributes}, session: valid_session
        expect(response).to redirect_to(dictionary)
      end
    end

    context "with invalid params" do
      it "assigns the dictionary as @dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, params: {id: dictionary.to_param, dictionary: invalid_attributes}, session: valid_session
        expect(assigns(:dictionary)).to eq(dictionary)
      end

      it "re-renders the 'edit' template" do
        dictionary = Dictionary.create! valid_attributes
        put :update, params: {id: dictionary.to_param, dictionary: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dictionary" do
      dictionary = Dictionary.create! valid_attributes
      expect {
        delete :destroy, params: {id: dictionary.to_param}, session: valid_session
      }.to change(Dictionary, :count).by(-1)
    end

    it "redirects to the dictionaries list" do
      dictionary = Dictionary.create! valid_attributes
      delete :destroy, params: {id: dictionary.to_param}, session: valid_session
      expect(response).to redirect_to(dictionaries_url)
    end
  end

end
